name: Matrix Strategy
on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node_version: [14, 16, 18]
        os_system: [ubuntu-latest, windows-latest]
        include:
          - node_version: 20
            os_system: ubuntu-latest
        exclude:
          - node_version: 14
            os_system: windows-latest
    runs-on: ${{ matrix.os_system }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node_version}}
      - name: Install dependencies
        run: npm ci
      - name: build project
        run: npm run build
