name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to upload
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list the files
        run: ls -lah
      - name: deploy the code
        run: echo "deploying and uploading"
